#
# .zlogout
# Executes Commands at Logout
#
# fr1volous
# Andrew Bell <andrewbell8@gmail.com>
#

# Print the message.
tdate = $(date +%y.%m.%d)

cat <<EOF logout.txt

Logging off Fr1volous
    -- ajb $tdate
EOF

