#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Andrew Bell <andrewbell8@gmail.com>
#

#
# Powerlevel9k
#

POWERLEVEL9K_MODE='nerdfont-complete'
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
#POWERLEVEL9K_SHORTEN_DELIMITER=""
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%F{white}"
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%F{blue}\u2570\uf460%F{white} "
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir dir_writable_joined)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time
                                    vcs background_jobs_joined time_joined)
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="clear"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="clear"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"
POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_FOREGROUND="blue"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="blue"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="red"
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="white"
POWERLEVEL9K_STATUS_OK_BACKGROUND="clear"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="clear"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
POWERLEVEL9K_TIME_BACKGROUND="clear"
POWERLEVEL9K_TIME_FOREGROUND="cyan"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='clear'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='magenta'
POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='clear'
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='green'

#
# user bin
#

if [[ -d "~/Dropbox/bin" ]]; then
    rm -rfv "${ZDOTDIR:-$HOME}"/bin && ln -sdv ~/Dropbox/bin "${ZDOTDIR:-$HOME}"/bin
fi


#
# macos path setup
#

if [[ $OSTYPE == *darwin* ]]; then
    # Ensure path arrays do not contain duplicates.
    typeset -gU cdpath dfpath mailpath path

    if [[ -f "$HOME"/.secrets ]]; then
        source "$HOME"/.secrets
    fi

    #
    # fpath
    #

    path=(
        "${ZDOTDIR:-$HOME}"/bin
        /usr/local/{bin,sbin}
        $path
    )

    export BROWSER='open'

    #
    # homebrew
    #

    if [[ -z $(which brew) ]]; then
        function install_homebrew() {
            ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        }

        install_homebrew
    fi

    export HOMEBREW_GITHUB_API_TOKEN="$MY_HOMEBREW_GITHUB_API_TOKEN"
    export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"
    export MANPATH="$(brew --prefix coreutils)/libexec/gnuman:/usr/local/share/man:$MANPATH"

    #
    # Java
    #

    JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
    CLASSPATH=".:$HOME/Library/Java/junit.jar:$CLASSPATH"
    export JAVA_HOME JAVA_OPTS CLASSPATH


    #
    # go
    #

    export GOPATH="$HOME"/.go
    export GOBIN="$GOPATH"/bin
    export PATH=$PATH:/usr/local/opt/go/libexec/bin


    #
    # nvm
    #

    export NVM_DIR="$HOME"/.nvm
    if [[ -s "$NVM_DIR"/nvm.sh ]]; then
        source "$NVM_DIR"/nvm.sh
    fi


#
# linux path setup
#

elif [[ $OSTYPE == *linux* ]]; then

    # Ensure path arrays do not contain duplicates.
    typeset -gU cdpath dfpath mailpath path

    export BROWSER='xdg-open'


    #
    # linuxbrew
    #

    PATH="$HOME/.linuxbrew/bin:$PATH"
    export PATH="$HOME/.linuxbrew/bin:$PATH"
    export MANPATH="$(brew --prefix)/share/man:$MANPATH"
    export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
    # export HOMEBREW_BUILD_FROM_SOURCE=1

    #
    # fpath
    #

    path=(
        "${ZDOTDIR:-$HOME}"/bin
        /usr/{bin,sbin}
        $path
    )


    #
    # go
    #

    export GOPATH="$HOME"/.go
    export GOBIN="$GOPATH"/bin
    export PATH=$PATH:/usr/opt/go/libexec/bin


    #
    # nvm
    #

    export NVM_DIR="$HOME/.nvm"

    if [[ -s "$HOME/.linuxbrew/opt/nvm/nvm.sh" ]]; then
        source "$HOME/.linuxbrew/opt/nvm/nvm.sh"
    fi

    # nvm completion
    if [[ -s "$HOME/.linuxbrew/etc/bash_completion.d/nvm" ]]; then
        source "$HOME/.linuxbrew/etc/bash_completion.d/nvm"
    fi
fi


#
# Gnupg
#

GPG_TTY=$(tty)
export GPG_TTY
export MYGPGKEY="$MY_GPG_KEY"
export QT_AUTO_SCREEN_SCALE_FACTOR=0


#
# Editors
#

export PAGER=less
export EDITOR='subl -n -w'
export VISUAL=$EDITOR
export GIT_EDITOR=$VISUAL
export SVN_EDITOR=$VISUAL
export HG_EDITOR=$VISUAL
export HOMEBREW_EDITOR=$VISUAL
export ___FULLUSERNAME___="Andrew Bell"
export ___ORGANIZATIONNAME___="Fr1v"
export SNIPPET_AUTHOR="Andrew Bell"
export LANG=en_US.UTF-8
umask 022


#
# rbenv
#
#

if [[ -d "$HOME/.rbenv" ]]; then
    export PROJECT_HOME="${ZDOTDIR:-$HOME}"/code
    export RBENV_ROOT="${ZDOTDIR:-$HOME}"/.rbenv
    export RBENV_DIR="$PWD"
    export PATH="$RBENV_ROOT/bin:$PATH"

    # rbenv init
    if which rbenv > /dev/null; then
        eval "$(rbenv init -)"
    fi

    # rbenv completions
    if [[ -f "$HOME/.rbenv/completions/rbenv.zsh" ]]; then
        source "$HOME/.rbenv/completions/rbenv.zsh"
    fi
fi


#
# pyenv
#

if [[ -d "$HOME/.pyenv" ]]; then
    export PYENV_ROOT="${ZDOTDIR:-$HOME}/.pyenv"
    export PYENV_DIR="$PWD"
    export PATH="$PYENV_ROOT/bin:$PATH"

    # pyenv init
    if which pyenv > /dev/null; then
        eval "$(pyenv init -)"
    fi

    # pyenv completions
    if [[ -f "$HOME/.pyenv/completions/pyenv.zsh" ]]; then
        source "$HOME/.pyenv/completions/pyenv.zsh"
    fi
fi


#
# pyenv-virtualenv
#

if which pyenv-virtualenv-init > /dev/null; then
    eval "$(pyenv virtualenv-init -)"
fi

export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'


#
# Rust
#

export RUST_SRC_PATH="$HOME/.multirust/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/rustlib/src/rust/src"
export PATH="$HOME/.cargo/bin:$PATH"


#
# Revolver Completion
#

if [[ -f "$HOME"/.zprezto/modules/Revolver/revolver.zsh-completion ]]; then
    source "$HOME"/.zprezto/modules/Revolver/revolver.zsh-completion
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='--tabs=4 --no-init --LONG-PROMPT --ignore-case --quit-if-one-screen --RAW-CONTROL-CHARS'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
    export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi


#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
    export TMPDIR="/tmp/$LOGNAME"
    mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
