#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Andrew Bell <andrewbell8@gmail.com>
#

# Working dir for developing
PROJECT_DIR=${HOME}/code

# BROWSER
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
  export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
  export MANPATH="$(brew --prefix coreutils)/libexec/gnuman:$MANPATH"
  export INFOPATH="$(brew --prefix coreutils)/libexec/gnuinfo:$INFOPATH"
elif [[ "$OSTYPE" == msys* ]]; then
  export BROWSER='explorer .'
elif [[ "$OSTYPE" == linux* ]]; then
  export PATH="$HOME/.linuxbrew/bin:$PATH"
  export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
fi

# EDITORS
export EDITOR='nvim'
export VISUAL='subl'
export PAGER='less'

# LANGUAGE
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Prevent these from being duplicates
typeset -gU cdpath fpath mailpath path

# CDPATH: Set the the list of directories that cd searches.
cdpath=(
  $cdpath
)

# PATH: Set the list of directories that Zsh searches for programs.
path=(
  $HOME/Dropbox/bin
  /usr/local/{bin,sbin}
  $path
)

# LESS
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# TEMP
if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

