# Customize to your needs...
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Pablo Olmos de Aguilera <pablo at glatelier dot org>
#   Andrew Bell <andrewbell8@gmail.com>
#

export TERM="xterm-256color"

if [[ $OSTYPE == *darwin* ]] ; then
	if [[ -f "${ZDOTDIR:-$HOME}/.secrets" ]]; then
	  source "${ZDOTDIR:-$HOME}/.secrets"
	fi
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zprofile" ]] ; then
	source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zpreztorc" ]]; then
  source "${ZDOTDIR:-$HOME}/.zpreztorc"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
else
  echo 'Prezto not installed!.'
fi
