#!/usr/local/bin/zsh
#
# packs supplied file(s) to 7z 
#
# Andrew Bell <andrewbell8@gmail.com>
# fr1v @ https://fr1v.github.io
#

function pto7z() {
    setopt LOCAL_OPTIONS EXTENDED_GLOB

    for f in "$@"
    do
        local file_ext=${f:e}
        apack -F.7z -O-m0=lzma2 -O-mx=9 -O-mfb=64 -O-md=32m -O-ms=on -q -e "$f"
        rm "${f}"
    done
    unset LOCAL_OPTIONS EXTENDED_GLOB
}

pto7z "$@"